name: unwrap_me
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/aimer63/unwrap_me

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
